import React, { useState, useEffect } from 'react';
import { View, Text, StyleSheet, ScrollView, ActivityIndicator } from 'react-native';
import licenses from '../client-licenses.json';
import { useFontSize } from '../context/fontSizeContext'; // ADD THIS IMPORT

export default function AboutScreen() {
    const [licenseData, setLicenseData] = useState([]);
    const [loading, setLoading] = useState(true);

    const { fontSize } = useFontSize(); // GET FONT SIZE FROM CONTEXT

    useEffect(() => {
        processLicenses();
    }, []);

    const processLicenses = () => {
        try {
            // Convert object to array and extract unique licenses
            const licensesArray = Object.entries(licenses).map(([name, info]) => ({
                name: name,
                license: info.licenses || 'Unknown',
            }));

            // Group by license type
            const grouped = {};
            licensesArray.forEach(item => {
                if (!grouped[item.license]) {
                    grouped[item.license] = [];
                }
                grouped[item.license].push(item.name);
            });

            // Convert to array and sort by license type
            const processed = Object.entries(grouped)
                .map(([license, packages]) => ({
                    license,
                    count: packages.length,
                    packages: packages.sort(),
                }))
                .sort((a, b) => b.count - a.count);

            setLicenseData(processed);
        } catch (error) {
            console.error('Error processing licenses:', error);
        } finally {
            setLoading(false);
        }
    };

    if (loading) {
        return (
            <View style={styles.centerContainer}>
                <ActivityIndicator size="large" color="#007AFF" />
            </View>
        );
    }

    return (
        <ScrollView style={styles.container}>
            <Text style={styles.title}>Note Taking App</Text>
            <Text style={[styles.description, fontSize === 'big' ? styles.bigText : styles.smallText]}>
                This application allows you to efficiently create, manage, and access your personal notes.
            </Text>

            <Text style={[styles.subTitle, fontSize === 'big' ? styles.bigSubTitle : styles.smallSubTitle]}>Features:</Text>
            <Text style={[styles.feature, fontSize === 'big' ? styles.bigText : styles.smallText]}>• Create and edit your notes with ease.</Text>
            <Text style={[styles.feature, fontSize === 'big' ? styles.bigText : styles.smallText]}>• Organize notes by user-specific categories.</Text>
            <Text style={[styles.feature, fontSize === 'big' ? styles.bigText : styles.smallText]}>• Secure your notes with user authentication.</Text>

            <Text style={[styles.subTitle, fontSize === 'big' ? styles.bigSubTitle : styles.smallSubTitle]}>Open Source Licenses:</Text>
            <Text style={[styles.licenseInfo, fontSize === 'big' ? styles.bigText : styles.smallText]}>
                This app uses {Object.keys(licenses).length} open source packages
            </Text>

            {licenseData.map((item, index) => (
                <View key={index} style={styles.licenseGroup}>
                    <Text style={[styles.licenseHeader, fontSize === 'big' ? styles.bigText : styles.smallText]}>
                        {item.license} ({item.count} packages)
                    </Text>
                    {item.packages.slice(0, 10).map((pkg, pkgIndex) => (
                        <Text key={pkgIndex} style={[styles.packageName, fontSize === 'big' ? styles.bigText : styles.smallText]}>
                            • {pkg}
                        </Text>
                    ))}
                    {item.count > 10 && (
                        <Text style={styles.morePackages}>
                            ... and {item.count - 10} more
                        </Text>
                    )}
                </View>
            ))}

            <Text style={[styles.footer, fontSize === 'big' ? styles.bigText : styles.smallText]}>
                Licenses generated by npm-license-crawler. @ 2025 Note Taking App.
            </Text>
        </ScrollView>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        padding: 20,
        backgroundColor: '#f5f5f5',
    },
    centerContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    title: {
        fontSize: 28,
        fontWeight: 'bold',
        marginTop: 20,
        marginBottom: 5,
        textAlign: 'center',
        color: '#007AFF',
    },
    version: {
        fontSize: 14,
        marginBottom: 15,
        textAlign: 'center',
        color: '#666',
    },
    description: {
        fontSize: 16,
        marginBottom: 20,
        textAlign: 'center',
        color: '#555',
        lineHeight: 24,
    },
    subTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        marginTop: 20,
        marginBottom: 10,
        color: '#007AFF',
    },
    smallSubTitle: {
        fontSize: 20,
    },
    bigSubTitle: {
        fontSize: 22,
    }
    ,
    feature: {
        fontSize: 16,
        marginBottom: 8,
        color: '#555',
        lineHeight: 22,
    },
    licenseInfo: {
        fontSize: 16,
        marginBottom: 15,
        color: '#555',
    },
    licenseGroup: {
        backgroundColor: '#fff',
        padding: 15,
        borderRadius: 6,
        marginBottom: 15,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
    },
    licenseHeader: {
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 8,
        color: '#007AFF',
    },
    packageName: {
        fontSize: 16,
        marginBottom: 4,
        marginLeft: 10,
        color: '#555',
    },
    morePackages: {
        fontSize: 16,
        marginTop: 5,
        marginLeft: 10,
        color: '#999',
        fontStyle: 'italic',
    },
    footer: {
        fontSize: 16,
        marginTop: 10,
        marginBottom: 5,
        textAlign: 'center',
        color: '#999',
    },
    smallText: {
        fontSize: 16, // Default small font size
    },
    bigText: {
        fontSize: 20, // Larger font size
    },
});

