import React from 'react';
import { View, Text, StyleSheet, ScrollView } from 'react-native';

export default function AboutScreen() {
    return (
     <ScrollView style={styles.container}>
            <Text style={styles.title}>Note Taking App</Text>
            <Text style={styles.description}>
                This application allows you to efficiently create, manage, and access your personal notes.
            </Text>
            
            <Text style={styles.subTitle}>Features:</Text>
            <Text style={styles.feature}>• Create and edit your notes with ease.</Text>
            <Text style={styles.feature}>• Organize notes by user-specific categories.</Text>
            <Text style={styles.feature}>• Secure your notes with user authentication.</Text>

            <Text style={styles.subTitle}>Open Source Licenses:</Text>
            <Text style={styles.license}>• axios: MIT License</Text>
            <Text style={styles.license}>• expo: MIT License</Text>
            <Text style={styles.license}>• react: MIT License</Text>
            <Text style={styles.license}>• react-native: MIT License</Text>
            <Text style={styles.license}>• react-navigation: MIT License</Text>
            <Text style={styles.license}>• @react-native-async-storage/async-storage: MIT License</Text>

            <Text style={styles.footer}>Licenses generated by npm-license-crawler</Text>
        </ScrollView>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        padding: 20,
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        marginBottom: 20,
    },
     description: {
        fontSize: 16,
        marginBottom: 15,
        textAlign: 'center',
    },
    subTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        marginVertical: 10,
    },
    feature: {
        fontSize: 16,
        marginBottom: 5,
    },
    license: {
        fontSize: 16,
        marginBottom: 5,
        marginLeft: 10,
    },
    footer: {
        fontSize: 12,
        marginTop: 15,
        textAlign: 'center',
        color: 'gray',
    },
});